#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFParsing
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_PDFParsing")]
	public partial class PDFParseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCATEGORY(CATEGORY instance);
    partial void UpdateCATEGORY(CATEGORY instance);
    partial void DeleteCATEGORY(CATEGORY instance);
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    partial void InsertDOCUMENT_CATEGORY(DOCUMENT_CATEGORY instance);
    partial void UpdateDOCUMENT_CATEGORY(DOCUMENT_CATEGORY instance);
    partial void DeleteDOCUMENT_CATEGORY(DOCUMENT_CATEGORY instance);
    partial void InsertDOCUMENT_METATAG(DOCUMENT_METATAG instance);
    partial void UpdateDOCUMENT_METATAG(DOCUMENT_METATAG instance);
    partial void DeleteDOCUMENT_METATAG(DOCUMENT_METATAG instance);
    partial void InsertDOCUMENT(DOCUMENT instance);
    partial void UpdateDOCUMENT(DOCUMENT instance);
    partial void DeleteDOCUMENT(DOCUMENT instance);
    partial void InsertPARSER_DOCUMENT(PARSER_DOCUMENT instance);
    partial void UpdatePARSER_DOCUMENT(PARSER_DOCUMENT instance);
    partial void DeletePARSER_DOCUMENT(PARSER_DOCUMENT instance);
    partial void InsertPARSER_SHEET(PARSER_SHEET instance);
    partial void UpdatePARSER_SHEET(PARSER_SHEET instance);
    partial void DeletePARSER_SHEET(PARSER_SHEET instance);
    partial void InsertUSER_CATEGORY(USER_CATEGORY instance);
    partial void UpdateUSER_CATEGORY(USER_CATEGORY instance);
    partial void DeleteUSER_CATEGORY(USER_CATEGORY instance);
    #endregion
		
		public PDFParseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_PDFParsingConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PDFParseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PDFParseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PDFParseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PDFParseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CATEGORY> CATEGORies
		{
			get
			{
				return this.GetTable<CATEGORY>();
			}
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
		
		public System.Data.Linq.Table<DOCUMENT_CATEGORY> DOCUMENT_CATEGORies
		{
			get
			{
				return this.GetTable<DOCUMENT_CATEGORY>();
			}
		}
		
		public System.Data.Linq.Table<DOCUMENT_METATAG> DOCUMENT_METATAGs
		{
			get
			{
				return this.GetTable<DOCUMENT_METATAG>();
			}
		}
		
		public System.Data.Linq.Table<DOCUMENT> DOCUMENTs
		{
			get
			{
				return this.GetTable<DOCUMENT>();
			}
		}
		
		public System.Data.Linq.Table<PARSER_DOCUMENT> PARSER_DOCUMENTs
		{
			get
			{
				return this.GetTable<PARSER_DOCUMENT>();
			}
		}
		
		public System.Data.Linq.Table<PARSER_SHEET> PARSER_SHEETs
		{
			get
			{
				return this.GetTable<PARSER_SHEET>();
			}
		}
		
		public System.Data.Linq.Table<USER_CATEGORY> USER_CATEGORies
		{
			get
			{
				return this.GetTable<USER_CATEGORY>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetReport")]
		public ISingleResult<GetReportResult> GetReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARSER_ID", DbType="Int")] System.Nullable<int> pARSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pARSER_ID);
			return ((ISingleResult<GetReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetReport_USER")]
		public ISingleResult<GetReport_USERResult> GetReport_USER([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_ID);
			return ((ISingleResult<GetReport_USERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetReport_admin")]
		public ISingleResult<GetReport_adminResult> GetReport_admin()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetReport_adminResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAnalysis")]
		public ISingleResult<GetAnalysisResult> GetAnalysis([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARSER_ID", DbType="Int")] System.Nullable<int> pARSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEAR", DbType="Int")] System.Nullable<int> yEAR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MONTH", DbType="NVarChar(MAX)")] string mONTH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QUERY", DbType="Int")] System.Nullable<int> qUERY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pARSER_ID, yEAR, mONTH, qUERY);
			return ((ISingleResult<GetAnalysisResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CATEGORY")]
	public partial class CATEGORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CATEGORY_ID;
		
		private string _CATEGORY_NAME;
		
		private System.Nullable<int> _CATEGORY_TYPE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCATEGORY_IDChanging(int value);
    partial void OnCATEGORY_IDChanged();
    partial void OnCATEGORY_NAMEChanging(string value);
    partial void OnCATEGORY_NAMEChanged();
    partial void OnCATEGORY_TYPEChanging(System.Nullable<int> value);
    partial void OnCATEGORY_TYPEChanged();
    #endregion
		
		public CATEGORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CATEGORY_ID
		{
			get
			{
				return this._CATEGORY_ID;
			}
			set
			{
				if ((this._CATEGORY_ID != value))
				{
					this.OnCATEGORY_IDChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY_ID = value;
					this.SendPropertyChanged("CATEGORY_ID");
					this.OnCATEGORY_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_NAME", DbType="NVarChar(MAX)")]
		public string CATEGORY_NAME
		{
			get
			{
				return this._CATEGORY_NAME;
			}
			set
			{
				if ((this._CATEGORY_NAME != value))
				{
					this.OnCATEGORY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY_NAME = value;
					this.SendPropertyChanged("CATEGORY_NAME");
					this.OnCATEGORY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_TYPE", DbType="Int")]
		public System.Nullable<int> CATEGORY_TYPE
		{
			get
			{
				return this._CATEGORY_TYPE;
			}
			set
			{
				if ((this._CATEGORY_TYPE != value))
				{
					this.OnCATEGORY_TYPEChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY_TYPE = value;
					this.SendPropertyChanged("CATEGORY_TYPE");
					this.OnCATEGORY_TYPEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERS")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _USER_ID;
		
		private string _USERNAME;
		
		private string _EMAIL_ADDRESS;
		
		private string _PASSWORD;
		
		private System.Nullable<System.DateTime> _CREATE_DATE;
		
		private System.Nullable<bool> _IS_ADMIN;
		
		private System.Nullable<bool> _IS_ACTIVE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSER_IDChanging(int value);
    partial void OnUSER_IDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnEMAIL_ADDRESSChanging(string value);
    partial void OnEMAIL_ADDRESSChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnCREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DATEChanged();
    partial void OnIS_ADMINChanging(System.Nullable<bool> value);
    partial void OnIS_ADMINChanged();
    partial void OnIS_ACTIVEChanging(System.Nullable<bool> value);
    partial void OnIS_ACTIVEChanged();
    #endregion
		
		public USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(MAX)")]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_ADDRESS", DbType="NVarChar(MAX)")]
		public string EMAIL_ADDRESS
		{
			get
			{
				return this._EMAIL_ADDRESS;
			}
			set
			{
				if ((this._EMAIL_ADDRESS != value))
				{
					this.OnEMAIL_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_ADDRESS = value;
					this.SendPropertyChanged("EMAIL_ADDRESS");
					this.OnEMAIL_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(MAX)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_ADMIN", DbType="Bit")]
		public System.Nullable<bool> IS_ADMIN
		{
			get
			{
				return this._IS_ADMIN;
			}
			set
			{
				if ((this._IS_ADMIN != value))
				{
					this.OnIS_ADMINChanging(value);
					this.SendPropertyChanging();
					this._IS_ADMIN = value;
					this.SendPropertyChanged("IS_ADMIN");
					this.OnIS_ADMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_ACTIVE", DbType="Bit")]
		public System.Nullable<bool> IS_ACTIVE
		{
			get
			{
				return this._IS_ACTIVE;
			}
			set
			{
				if ((this._IS_ACTIVE != value))
				{
					this.OnIS_ACTIVEChanging(value);
					this.SendPropertyChanging();
					this._IS_ACTIVE = value;
					this.SendPropertyChanged("IS_ACTIVE");
					this.OnIS_ACTIVEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOCUMENT_CATEGORY")]
	public partial class DOCUMENT_CATEGORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NAME;
		
		private string _DOCUMENT_TYPE;
		
		private System.Nullable<bool> _IS_CREDIT;
		
		private System.Nullable<bool> _IS_DEBIT;
		
		private string _CATEGORY_TYPE;
		
		private string _IDENTIFIER_1;
		
		private string _IDENTIFIER_2;
		
		private string _IDENTIFIER_3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnDOCUMENT_TYPEChanging(string value);
    partial void OnDOCUMENT_TYPEChanged();
    partial void OnIS_CREDITChanging(System.Nullable<bool> value);
    partial void OnIS_CREDITChanged();
    partial void OnIS_DEBITChanging(System.Nullable<bool> value);
    partial void OnIS_DEBITChanged();
    partial void OnCATEGORY_TYPEChanging(string value);
    partial void OnCATEGORY_TYPEChanged();
    partial void OnIDENTIFIER_1Changing(string value);
    partial void OnIDENTIFIER_1Changed();
    partial void OnIDENTIFIER_2Changing(string value);
    partial void OnIDENTIFIER_2Changed();
    partial void OnIDENTIFIER_3Changing(string value);
    partial void OnIDENTIFIER_3Changed();
    #endregion
		
		public DOCUMENT_CATEGORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_TYPE", DbType="NVarChar(MAX)")]
		public string DOCUMENT_TYPE
		{
			get
			{
				return this._DOCUMENT_TYPE;
			}
			set
			{
				if ((this._DOCUMENT_TYPE != value))
				{
					this.OnDOCUMENT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._DOCUMENT_TYPE = value;
					this.SendPropertyChanged("DOCUMENT_TYPE");
					this.OnDOCUMENT_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_CREDIT", DbType="Bit")]
		public System.Nullable<bool> IS_CREDIT
		{
			get
			{
				return this._IS_CREDIT;
			}
			set
			{
				if ((this._IS_CREDIT != value))
				{
					this.OnIS_CREDITChanging(value);
					this.SendPropertyChanging();
					this._IS_CREDIT = value;
					this.SendPropertyChanged("IS_CREDIT");
					this.OnIS_CREDITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_DEBIT", DbType="Bit")]
		public System.Nullable<bool> IS_DEBIT
		{
			get
			{
				return this._IS_DEBIT;
			}
			set
			{
				if ((this._IS_DEBIT != value))
				{
					this.OnIS_DEBITChanging(value);
					this.SendPropertyChanging();
					this._IS_DEBIT = value;
					this.SendPropertyChanged("IS_DEBIT");
					this.OnIS_DEBITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_TYPE", DbType="NVarChar(MAX)")]
		public string CATEGORY_TYPE
		{
			get
			{
				return this._CATEGORY_TYPE;
			}
			set
			{
				if ((this._CATEGORY_TYPE != value))
				{
					this.OnCATEGORY_TYPEChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY_TYPE = value;
					this.SendPropertyChanged("CATEGORY_TYPE");
					this.OnCATEGORY_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFIER_1", DbType="NVarChar(MAX)")]
		public string IDENTIFIER_1
		{
			get
			{
				return this._IDENTIFIER_1;
			}
			set
			{
				if ((this._IDENTIFIER_1 != value))
				{
					this.OnIDENTIFIER_1Changing(value);
					this.SendPropertyChanging();
					this._IDENTIFIER_1 = value;
					this.SendPropertyChanged("IDENTIFIER_1");
					this.OnIDENTIFIER_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFIER_2", DbType="NVarChar(MAX)")]
		public string IDENTIFIER_2
		{
			get
			{
				return this._IDENTIFIER_2;
			}
			set
			{
				if ((this._IDENTIFIER_2 != value))
				{
					this.OnIDENTIFIER_2Changing(value);
					this.SendPropertyChanging();
					this._IDENTIFIER_2 = value;
					this.SendPropertyChanged("IDENTIFIER_2");
					this.OnIDENTIFIER_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFIER_3", DbType="NVarChar(MAX)")]
		public string IDENTIFIER_3
		{
			get
			{
				return this._IDENTIFIER_3;
			}
			set
			{
				if ((this._IDENTIFIER_3 != value))
				{
					this.OnIDENTIFIER_3Changing(value);
					this.SendPropertyChanging();
					this._IDENTIFIER_3 = value;
					this.SendPropertyChanged("IDENTIFIER_3");
					this.OnIDENTIFIER_3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOCUMENT_METATAGS")]
	public partial class DOCUMENT_METATAG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _DOCUMENT_ID;
		
		private string _TITLE;
		
		private string _VALUE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDOCUMENT_IDChanging(System.Nullable<int> value);
    partial void OnDOCUMENT_IDChanged();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    partial void OnVALUEChanging(string value);
    partial void OnVALUEChanged();
    #endregion
		
		public DOCUMENT_METATAG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_ID", DbType="Int")]
		public System.Nullable<int> DOCUMENT_ID
		{
			get
			{
				return this._DOCUMENT_ID;
			}
			set
			{
				if ((this._DOCUMENT_ID != value))
				{
					this.OnDOCUMENT_IDChanging(value);
					this.SendPropertyChanging();
					this._DOCUMENT_ID = value;
					this.SendPropertyChanged("DOCUMENT_ID");
					this.OnDOCUMENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="NVarChar(MAX)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE", DbType="NVarChar(MAX)")]
		public string VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this.OnVALUEChanging(value);
					this.SendPropertyChanging();
					this._VALUE = value;
					this.SendPropertyChanged("VALUE");
					this.OnVALUEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOCUMENTS")]
	public partial class DOCUMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DOCUMENT_ID;
		
		private System.Nullable<int> _USER_ID;
		
		private string _DOCUMENT_NAME;
		
		private string _DOCUMENT_TYPE;
		
		private string _ACCOUNT_TYPE;
		
		private System.Nullable<System.DateTime> _UPLOAD_DATE;
		
		private System.Nullable<bool> _IS_PASSWORD_PROTECTED;
		
		private string _PASSWORD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDOCUMENT_IDChanging(int value);
    partial void OnDOCUMENT_IDChanged();
    partial void OnUSER_IDChanging(System.Nullable<int> value);
    partial void OnUSER_IDChanged();
    partial void OnDOCUMENT_NAMEChanging(string value);
    partial void OnDOCUMENT_NAMEChanged();
    partial void OnDOCUMENT_TYPEChanging(string value);
    partial void OnDOCUMENT_TYPEChanged();
    partial void OnACCOUNT_TYPEChanging(string value);
    partial void OnACCOUNT_TYPEChanged();
    partial void OnUPLOAD_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPLOAD_DATEChanged();
    partial void OnIS_PASSWORD_PROTECTEDChanging(System.Nullable<bool> value);
    partial void OnIS_PASSWORD_PROTECTEDChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    #endregion
		
		public DOCUMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DOCUMENT_ID
		{
			get
			{
				return this._DOCUMENT_ID;
			}
			set
			{
				if ((this._DOCUMENT_ID != value))
				{
					this.OnDOCUMENT_IDChanging(value);
					this.SendPropertyChanging();
					this._DOCUMENT_ID = value;
					this.SendPropertyChanged("DOCUMENT_ID");
					this.OnDOCUMENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="Int")]
		public System.Nullable<int> USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_NAME", DbType="NVarChar(MAX)")]
		public string DOCUMENT_NAME
		{
			get
			{
				return this._DOCUMENT_NAME;
			}
			set
			{
				if ((this._DOCUMENT_NAME != value))
				{
					this.OnDOCUMENT_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DOCUMENT_NAME = value;
					this.SendPropertyChanged("DOCUMENT_NAME");
					this.OnDOCUMENT_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_TYPE", DbType="NVarChar(MAX)")]
		public string DOCUMENT_TYPE
		{
			get
			{
				return this._DOCUMENT_TYPE;
			}
			set
			{
				if ((this._DOCUMENT_TYPE != value))
				{
					this.OnDOCUMENT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._DOCUMENT_TYPE = value;
					this.SendPropertyChanged("DOCUMENT_TYPE");
					this.OnDOCUMENT_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_TYPE", DbType="NVarChar(MAX)")]
		public string ACCOUNT_TYPE
		{
			get
			{
				return this._ACCOUNT_TYPE;
			}
			set
			{
				if ((this._ACCOUNT_TYPE != value))
				{
					this.OnACCOUNT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT_TYPE = value;
					this.SendPropertyChanged("ACCOUNT_TYPE");
					this.OnACCOUNT_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPLOAD_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPLOAD_DATE
		{
			get
			{
				return this._UPLOAD_DATE;
			}
			set
			{
				if ((this._UPLOAD_DATE != value))
				{
					this.OnUPLOAD_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPLOAD_DATE = value;
					this.SendPropertyChanged("UPLOAD_DATE");
					this.OnUPLOAD_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_PASSWORD_PROTECTED", DbType="Bit")]
		public System.Nullable<bool> IS_PASSWORD_PROTECTED
		{
			get
			{
				return this._IS_PASSWORD_PROTECTED;
			}
			set
			{
				if ((this._IS_PASSWORD_PROTECTED != value))
				{
					this.OnIS_PASSWORD_PROTECTEDChanging(value);
					this.SendPropertyChanging();
					this._IS_PASSWORD_PROTECTED = value;
					this.SendPropertyChanged("IS_PASSWORD_PROTECTED");
					this.OnIS_PASSWORD_PROTECTEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(MAX)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PARSER_DOCUMENT")]
	public partial class PARSER_DOCUMENT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PARSER_ID;
		
		private System.Nullable<int> _DOCUMENT_ID;
		
		private string _PARSER_NAME;
		
		private string _ADDRESS1;
		
		private string _ADDRESS2;
		
		private string _ADDRESS3;
		
		private string _CITY;
		
		private string _STATE;
		
		private string _ACCOUNT_BRANCH;
		
		private string _BRANCH_ADDRESS;
		
		private string _BRANCH_CITY;
		
		private string _BRANCH_STATE;
		
		private string _BRANCH_PHONENO;
		
		private string _CURRENCY;
		
		private string _EMAIL;
		
		private string _CUSTID;
		
		private string _ACCOUNTNO;
		
		private string _ACCOUNT_OPEN_DATE;
		
		private string _ACCOUNT_STATUS;
		
		private string _BRANCH_CODE;
		
		private string _PRODUCT_CODE;
		
		private string _NOMINATION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPARSER_IDChanging(int value);
    partial void OnPARSER_IDChanged();
    partial void OnDOCUMENT_IDChanging(System.Nullable<int> value);
    partial void OnDOCUMENT_IDChanged();
    partial void OnPARSER_NAMEChanging(string value);
    partial void OnPARSER_NAMEChanged();
    partial void OnADDRESS1Changing(string value);
    partial void OnADDRESS1Changed();
    partial void OnADDRESS2Changing(string value);
    partial void OnADDRESS2Changed();
    partial void OnADDRESS3Changing(string value);
    partial void OnADDRESS3Changed();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnSTATEChanging(string value);
    partial void OnSTATEChanged();
    partial void OnACCOUNT_BRANCHChanging(string value);
    partial void OnACCOUNT_BRANCHChanged();
    partial void OnBRANCH_ADDRESSChanging(string value);
    partial void OnBRANCH_ADDRESSChanged();
    partial void OnBRANCH_CITYChanging(string value);
    partial void OnBRANCH_CITYChanged();
    partial void OnBRANCH_STATEChanging(string value);
    partial void OnBRANCH_STATEChanged();
    partial void OnBRANCH_PHONENOChanging(string value);
    partial void OnBRANCH_PHONENOChanged();
    partial void OnCURRENCYChanging(string value);
    partial void OnCURRENCYChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnCUSTIDChanging(string value);
    partial void OnCUSTIDChanged();
    partial void OnACCOUNTNOChanging(string value);
    partial void OnACCOUNTNOChanged();
    partial void OnACCOUNT_OPEN_DATEChanging(string value);
    partial void OnACCOUNT_OPEN_DATEChanged();
    partial void OnACCOUNT_STATUSChanging(string value);
    partial void OnACCOUNT_STATUSChanged();
    partial void OnBRANCH_CODEChanging(string value);
    partial void OnBRANCH_CODEChanged();
    partial void OnPRODUCT_CODEChanging(string value);
    partial void OnPRODUCT_CODEChanged();
    partial void OnNOMINATIONChanging(string value);
    partial void OnNOMINATIONChanged();
    #endregion
		
		public PARSER_DOCUMENT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARSER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PARSER_ID
		{
			get
			{
				return this._PARSER_ID;
			}
			set
			{
				if ((this._PARSER_ID != value))
				{
					this.OnPARSER_IDChanging(value);
					this.SendPropertyChanging();
					this._PARSER_ID = value;
					this.SendPropertyChanged("PARSER_ID");
					this.OnPARSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_ID", DbType="Int")]
		public System.Nullable<int> DOCUMENT_ID
		{
			get
			{
				return this._DOCUMENT_ID;
			}
			set
			{
				if ((this._DOCUMENT_ID != value))
				{
					this.OnDOCUMENT_IDChanging(value);
					this.SendPropertyChanging();
					this._DOCUMENT_ID = value;
					this.SendPropertyChanged("DOCUMENT_ID");
					this.OnDOCUMENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARSER_NAME", DbType="NVarChar(MAX)")]
		public string PARSER_NAME
		{
			get
			{
				return this._PARSER_NAME;
			}
			set
			{
				if ((this._PARSER_NAME != value))
				{
					this.OnPARSER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PARSER_NAME = value;
					this.SendPropertyChanged("PARSER_NAME");
					this.OnPARSER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS1", DbType="NVarChar(MAX)")]
		public string ADDRESS1
		{
			get
			{
				return this._ADDRESS1;
			}
			set
			{
				if ((this._ADDRESS1 != value))
				{
					this.OnADDRESS1Changing(value);
					this.SendPropertyChanging();
					this._ADDRESS1 = value;
					this.SendPropertyChanged("ADDRESS1");
					this.OnADDRESS1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS2", DbType="NVarChar(MAX)")]
		public string ADDRESS2
		{
			get
			{
				return this._ADDRESS2;
			}
			set
			{
				if ((this._ADDRESS2 != value))
				{
					this.OnADDRESS2Changing(value);
					this.SendPropertyChanging();
					this._ADDRESS2 = value;
					this.SendPropertyChanged("ADDRESS2");
					this.OnADDRESS2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS3", DbType="NVarChar(MAX)")]
		public string ADDRESS3
		{
			get
			{
				return this._ADDRESS3;
			}
			set
			{
				if ((this._ADDRESS3 != value))
				{
					this.OnADDRESS3Changing(value);
					this.SendPropertyChanging();
					this._ADDRESS3 = value;
					this.SendPropertyChanged("ADDRESS3");
					this.OnADDRESS3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(MAX)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="NVarChar(MAX)")]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this.OnSTATEChanging(value);
					this.SendPropertyChanging();
					this._STATE = value;
					this.SendPropertyChanged("STATE");
					this.OnSTATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_BRANCH", DbType="NVarChar(MAX)")]
		public string ACCOUNT_BRANCH
		{
			get
			{
				return this._ACCOUNT_BRANCH;
			}
			set
			{
				if ((this._ACCOUNT_BRANCH != value))
				{
					this.OnACCOUNT_BRANCHChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT_BRANCH = value;
					this.SendPropertyChanged("ACCOUNT_BRANCH");
					this.OnACCOUNT_BRANCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_ADDRESS", DbType="NVarChar(MAX)")]
		public string BRANCH_ADDRESS
		{
			get
			{
				return this._BRANCH_ADDRESS;
			}
			set
			{
				if ((this._BRANCH_ADDRESS != value))
				{
					this.OnBRANCH_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_ADDRESS = value;
					this.SendPropertyChanged("BRANCH_ADDRESS");
					this.OnBRANCH_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CITY", DbType="NVarChar(MAX)")]
		public string BRANCH_CITY
		{
			get
			{
				return this._BRANCH_CITY;
			}
			set
			{
				if ((this._BRANCH_CITY != value))
				{
					this.OnBRANCH_CITYChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_CITY = value;
					this.SendPropertyChanged("BRANCH_CITY");
					this.OnBRANCH_CITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_STATE", DbType="NVarChar(MAX)")]
		public string BRANCH_STATE
		{
			get
			{
				return this._BRANCH_STATE;
			}
			set
			{
				if ((this._BRANCH_STATE != value))
				{
					this.OnBRANCH_STATEChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_STATE = value;
					this.SendPropertyChanged("BRANCH_STATE");
					this.OnBRANCH_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_PHONENO", DbType="NVarChar(MAX)")]
		public string BRANCH_PHONENO
		{
			get
			{
				return this._BRANCH_PHONENO;
			}
			set
			{
				if ((this._BRANCH_PHONENO != value))
				{
					this.OnBRANCH_PHONENOChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_PHONENO = value;
					this.SendPropertyChanged("BRANCH_PHONENO");
					this.OnBRANCH_PHONENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCY", DbType="NVarChar(MAX)")]
		public string CURRENCY
		{
			get
			{
				return this._CURRENCY;
			}
			set
			{
				if ((this._CURRENCY != value))
				{
					this.OnCURRENCYChanging(value);
					this.SendPropertyChanging();
					this._CURRENCY = value;
					this.SendPropertyChanged("CURRENCY");
					this.OnCURRENCYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(MAX)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTID", DbType="NVarChar(MAX)")]
		public string CUSTID
		{
			get
			{
				return this._CUSTID;
			}
			set
			{
				if ((this._CUSTID != value))
				{
					this.OnCUSTIDChanging(value);
					this.SendPropertyChanging();
					this._CUSTID = value;
					this.SendPropertyChanged("CUSTID");
					this.OnCUSTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNTNO", DbType="NVarChar(MAX)")]
		public string ACCOUNTNO
		{
			get
			{
				return this._ACCOUNTNO;
			}
			set
			{
				if ((this._ACCOUNTNO != value))
				{
					this.OnACCOUNTNOChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNTNO = value;
					this.SendPropertyChanged("ACCOUNTNO");
					this.OnACCOUNTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_OPEN_DATE", DbType="NVarChar(MAX)")]
		public string ACCOUNT_OPEN_DATE
		{
			get
			{
				return this._ACCOUNT_OPEN_DATE;
			}
			set
			{
				if ((this._ACCOUNT_OPEN_DATE != value))
				{
					this.OnACCOUNT_OPEN_DATEChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT_OPEN_DATE = value;
					this.SendPropertyChanged("ACCOUNT_OPEN_DATE");
					this.OnACCOUNT_OPEN_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_STATUS", DbType="NVarChar(MAX)")]
		public string ACCOUNT_STATUS
		{
			get
			{
				return this._ACCOUNT_STATUS;
			}
			set
			{
				if ((this._ACCOUNT_STATUS != value))
				{
					this.OnACCOUNT_STATUSChanging(value);
					this.SendPropertyChanging();
					this._ACCOUNT_STATUS = value;
					this.SendPropertyChanged("ACCOUNT_STATUS");
					this.OnACCOUNT_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CODE", DbType="NVarChar(MAX)")]
		public string BRANCH_CODE
		{
			get
			{
				return this._BRANCH_CODE;
			}
			set
			{
				if ((this._BRANCH_CODE != value))
				{
					this.OnBRANCH_CODEChanging(value);
					this.SendPropertyChanging();
					this._BRANCH_CODE = value;
					this.SendPropertyChanged("BRANCH_CODE");
					this.OnBRANCH_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_CODE", DbType="NVarChar(MAX)")]
		public string PRODUCT_CODE
		{
			get
			{
				return this._PRODUCT_CODE;
			}
			set
			{
				if ((this._PRODUCT_CODE != value))
				{
					this.OnPRODUCT_CODEChanging(value);
					this.SendPropertyChanging();
					this._PRODUCT_CODE = value;
					this.SendPropertyChanged("PRODUCT_CODE");
					this.OnPRODUCT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMINATION", DbType="NVarChar(MAX)")]
		public string NOMINATION
		{
			get
			{
				return this._NOMINATION;
			}
			set
			{
				if ((this._NOMINATION != value))
				{
					this.OnNOMINATIONChanging(value);
					this.SendPropertyChanging();
					this._NOMINATION = value;
					this.SendPropertyChanged("NOMINATION");
					this.OnNOMINATIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PARSER_SHEET")]
	public partial class PARSER_SHEET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SHEET_ID;
		
		private System.Nullable<int> _PARSER_ID;
		
		private System.Nullable<System.DateTime> _DATE;
		
		private string _NARRATION;
		
		private string _CHQ_NO;
		
		private System.Nullable<System.DateTime> _VALUE_DATE;
		
		private System.Nullable<decimal> _WITHDRAWAL_AMOUNT;
		
		private System.Nullable<decimal> _DEPOSIT_AMOUNT;
		
		private System.Nullable<decimal> _CLOSING_BALANCE;
		
		private System.Nullable<int> _CATEGORY_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSHEET_IDChanging(int value);
    partial void OnSHEET_IDChanged();
    partial void OnPARSER_IDChanging(System.Nullable<int> value);
    partial void OnPARSER_IDChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    partial void OnNARRATIONChanging(string value);
    partial void OnNARRATIONChanged();
    partial void OnCHQ_NOChanging(string value);
    partial void OnCHQ_NOChanged();
    partial void OnVALUE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnVALUE_DATEChanged();
    partial void OnWITHDRAWAL_AMOUNTChanging(System.Nullable<decimal> value);
    partial void OnWITHDRAWAL_AMOUNTChanged();
    partial void OnDEPOSIT_AMOUNTChanging(System.Nullable<decimal> value);
    partial void OnDEPOSIT_AMOUNTChanged();
    partial void OnCLOSING_BALANCEChanging(System.Nullable<decimal> value);
    partial void OnCLOSING_BALANCEChanged();
    partial void OnCATEGORY_IDChanging(System.Nullable<int> value);
    partial void OnCATEGORY_IDChanged();
    #endregion
		
		public PARSER_SHEET()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHEET_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SHEET_ID
		{
			get
			{
				return this._SHEET_ID;
			}
			set
			{
				if ((this._SHEET_ID != value))
				{
					this.OnSHEET_IDChanging(value);
					this.SendPropertyChanging();
					this._SHEET_ID = value;
					this.SendPropertyChanged("SHEET_ID");
					this.OnSHEET_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARSER_ID", DbType="Int")]
		public System.Nullable<int> PARSER_ID
		{
			get
			{
				return this._PARSER_ID;
			}
			set
			{
				if ((this._PARSER_ID != value))
				{
					this.OnPARSER_IDChanging(value);
					this.SendPropertyChanging();
					this._PARSER_ID = value;
					this.SendPropertyChanged("PARSER_ID");
					this.OnPARSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NARRATION", DbType="NVarChar(MAX)")]
		public string NARRATION
		{
			get
			{
				return this._NARRATION;
			}
			set
			{
				if ((this._NARRATION != value))
				{
					this.OnNARRATIONChanging(value);
					this.SendPropertyChanging();
					this._NARRATION = value;
					this.SendPropertyChanged("NARRATION");
					this.OnNARRATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHQ_NO", DbType="NVarChar(MAX)")]
		public string CHQ_NO
		{
			get
			{
				return this._CHQ_NO;
			}
			set
			{
				if ((this._CHQ_NO != value))
				{
					this.OnCHQ_NOChanging(value);
					this.SendPropertyChanging();
					this._CHQ_NO = value;
					this.SendPropertyChanged("CHQ_NO");
					this.OnCHQ_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE_DATE", DbType="Date")]
		public System.Nullable<System.DateTime> VALUE_DATE
		{
			get
			{
				return this._VALUE_DATE;
			}
			set
			{
				if ((this._VALUE_DATE != value))
				{
					this.OnVALUE_DATEChanging(value);
					this.SendPropertyChanging();
					this._VALUE_DATE = value;
					this.SendPropertyChanged("VALUE_DATE");
					this.OnVALUE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WITHDRAWAL_AMOUNT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> WITHDRAWAL_AMOUNT
		{
			get
			{
				return this._WITHDRAWAL_AMOUNT;
			}
			set
			{
				if ((this._WITHDRAWAL_AMOUNT != value))
				{
					this.OnWITHDRAWAL_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._WITHDRAWAL_AMOUNT = value;
					this.SendPropertyChanged("WITHDRAWAL_AMOUNT");
					this.OnWITHDRAWAL_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPOSIT_AMOUNT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> DEPOSIT_AMOUNT
		{
			get
			{
				return this._DEPOSIT_AMOUNT;
			}
			set
			{
				if ((this._DEPOSIT_AMOUNT != value))
				{
					this.OnDEPOSIT_AMOUNTChanging(value);
					this.SendPropertyChanging();
					this._DEPOSIT_AMOUNT = value;
					this.SendPropertyChanged("DEPOSIT_AMOUNT");
					this.OnDEPOSIT_AMOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSING_BALANCE", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CLOSING_BALANCE
		{
			get
			{
				return this._CLOSING_BALANCE;
			}
			set
			{
				if ((this._CLOSING_BALANCE != value))
				{
					this.OnCLOSING_BALANCEChanging(value);
					this.SendPropertyChanging();
					this._CLOSING_BALANCE = value;
					this.SendPropertyChanged("CLOSING_BALANCE");
					this.OnCLOSING_BALANCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_ID", DbType="Int")]
		public System.Nullable<int> CATEGORY_ID
		{
			get
			{
				return this._CATEGORY_ID;
			}
			set
			{
				if ((this._CATEGORY_ID != value))
				{
					this.OnCATEGORY_IDChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY_ID = value;
					this.SendPropertyChanged("CATEGORY_ID");
					this.OnCATEGORY_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USER_CATEGORY")]
	public partial class USER_CATEGORY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _USER_ID;
		
		private string _NAME;
		
		private string _DOCUMENT_TYPE;
		
		private System.Nullable<bool> _IS_CREDIT;
		
		private System.Nullable<bool> _IS_DEDIT;
		
		private string _CATEGORY_TYPE;
		
		private string _IDENTIFIER_1;
		
		private string _IDENTIFIER_2;
		
		private string _IDENTIFIER_3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUSER_IDChanging(System.Nullable<int> value);
    partial void OnUSER_IDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnDOCUMENT_TYPEChanging(string value);
    partial void OnDOCUMENT_TYPEChanged();
    partial void OnIS_CREDITChanging(System.Nullable<bool> value);
    partial void OnIS_CREDITChanged();
    partial void OnIS_DEDITChanging(System.Nullable<bool> value);
    partial void OnIS_DEDITChanged();
    partial void OnCATEGORY_TYPEChanging(string value);
    partial void OnCATEGORY_TYPEChanged();
    partial void OnIDENTIFIER_1Changing(string value);
    partial void OnIDENTIFIER_1Changed();
    partial void OnIDENTIFIER_2Changing(string value);
    partial void OnIDENTIFIER_2Changed();
    partial void OnIDENTIFIER_3Changing(string value);
    partial void OnIDENTIFIER_3Changed();
    #endregion
		
		public USER_CATEGORY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="Int")]
		public System.Nullable<int> USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOCUMENT_TYPE", DbType="NVarChar(MAX)")]
		public string DOCUMENT_TYPE
		{
			get
			{
				return this._DOCUMENT_TYPE;
			}
			set
			{
				if ((this._DOCUMENT_TYPE != value))
				{
					this.OnDOCUMENT_TYPEChanging(value);
					this.SendPropertyChanging();
					this._DOCUMENT_TYPE = value;
					this.SendPropertyChanged("DOCUMENT_TYPE");
					this.OnDOCUMENT_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_CREDIT", DbType="Bit")]
		public System.Nullable<bool> IS_CREDIT
		{
			get
			{
				return this._IS_CREDIT;
			}
			set
			{
				if ((this._IS_CREDIT != value))
				{
					this.OnIS_CREDITChanging(value);
					this.SendPropertyChanging();
					this._IS_CREDIT = value;
					this.SendPropertyChanged("IS_CREDIT");
					this.OnIS_CREDITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_DEDIT", DbType="Bit")]
		public System.Nullable<bool> IS_DEDIT
		{
			get
			{
				return this._IS_DEDIT;
			}
			set
			{
				if ((this._IS_DEDIT != value))
				{
					this.OnIS_DEDITChanging(value);
					this.SendPropertyChanging();
					this._IS_DEDIT = value;
					this.SendPropertyChanged("IS_DEDIT");
					this.OnIS_DEDITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORY_TYPE", DbType="NVarChar(MAX)")]
		public string CATEGORY_TYPE
		{
			get
			{
				return this._CATEGORY_TYPE;
			}
			set
			{
				if ((this._CATEGORY_TYPE != value))
				{
					this.OnCATEGORY_TYPEChanging(value);
					this.SendPropertyChanging();
					this._CATEGORY_TYPE = value;
					this.SendPropertyChanged("CATEGORY_TYPE");
					this.OnCATEGORY_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFIER_1", DbType="NVarChar(MAX)")]
		public string IDENTIFIER_1
		{
			get
			{
				return this._IDENTIFIER_1;
			}
			set
			{
				if ((this._IDENTIFIER_1 != value))
				{
					this.OnIDENTIFIER_1Changing(value);
					this.SendPropertyChanging();
					this._IDENTIFIER_1 = value;
					this.SendPropertyChanged("IDENTIFIER_1");
					this.OnIDENTIFIER_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFIER_2", DbType="NVarChar(MAX)")]
		public string IDENTIFIER_2
		{
			get
			{
				return this._IDENTIFIER_2;
			}
			set
			{
				if ((this._IDENTIFIER_2 != value))
				{
					this.OnIDENTIFIER_2Changing(value);
					this.SendPropertyChanging();
					this._IDENTIFIER_2 = value;
					this.SendPropertyChanged("IDENTIFIER_2");
					this.OnIDENTIFIER_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFIER_3", DbType="NVarChar(MAX)")]
		public string IDENTIFIER_3
		{
			get
			{
				return this._IDENTIFIER_3;
			}
			set
			{
				if ((this._IDENTIFIER_3 != value))
				{
					this.OnIDENTIFIER_3Changing(value);
					this.SendPropertyChanging();
					this._IDENTIFIER_3 = value;
					this.SendPropertyChanged("IDENTIFIER_3");
					this.OnIDENTIFIER_3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetReportResult
	{
		
		private System.Nullable<int> _RYEAR;
		
		private string _RMONTH;
		
		private System.Nullable<int> _RMONTH1;
		
		private System.Nullable<decimal> _WITHDRAWAL_AMOUNT;
		
		private System.Nullable<decimal> _DEPOSIT_AMOUNT;
		
		private System.Nullable<decimal> _CLOSING_BALANCE;
		
		public GetReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYEAR", DbType="Int")]
		public System.Nullable<int> RYEAR
		{
			get
			{
				return this._RYEAR;
			}
			set
			{
				if ((this._RYEAR != value))
				{
					this._RYEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMONTH", DbType="NVarChar(30)")]
		public string RMONTH
		{
			get
			{
				return this._RMONTH;
			}
			set
			{
				if ((this._RMONTH != value))
				{
					this._RMONTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMONTH1", DbType="Int")]
		public System.Nullable<int> RMONTH1
		{
			get
			{
				return this._RMONTH1;
			}
			set
			{
				if ((this._RMONTH1 != value))
				{
					this._RMONTH1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WITHDRAWAL_AMOUNT", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> WITHDRAWAL_AMOUNT
		{
			get
			{
				return this._WITHDRAWAL_AMOUNT;
			}
			set
			{
				if ((this._WITHDRAWAL_AMOUNT != value))
				{
					this._WITHDRAWAL_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPOSIT_AMOUNT", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> DEPOSIT_AMOUNT
		{
			get
			{
				return this._DEPOSIT_AMOUNT;
			}
			set
			{
				if ((this._DEPOSIT_AMOUNT != value))
				{
					this._DEPOSIT_AMOUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLOSING_BALANCE", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> CLOSING_BALANCE
		{
			get
			{
				return this._CLOSING_BALANCE;
			}
			set
			{
				if ((this._CLOSING_BALANCE != value))
				{
					this._CLOSING_BALANCE = value;
				}
			}
		}
	}
	
	public partial class GetReport_USERResult
	{
		
		private System.Nullable<int> _RYEAR;
		
		private string _RMONTH;
		
		private System.Nullable<int> _RMONTH1;
		
		private System.Nullable<int> _Document_Uploaded;
		
		public GetReport_USERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYEAR", DbType="Int")]
		public System.Nullable<int> RYEAR
		{
			get
			{
				return this._RYEAR;
			}
			set
			{
				if ((this._RYEAR != value))
				{
					this._RYEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMONTH", DbType="NVarChar(30)")]
		public string RMONTH
		{
			get
			{
				return this._RMONTH;
			}
			set
			{
				if ((this._RMONTH != value))
				{
					this._RMONTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMONTH1", DbType="Int")]
		public System.Nullable<int> RMONTH1
		{
			get
			{
				return this._RMONTH1;
			}
			set
			{
				if ((this._RMONTH1 != value))
				{
					this._RMONTH1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Document_Uploaded", DbType="Int")]
		public System.Nullable<int> Document_Uploaded
		{
			get
			{
				return this._Document_Uploaded;
			}
			set
			{
				if ((this._Document_Uploaded != value))
				{
					this._Document_Uploaded = value;
				}
			}
		}
	}
	
	public partial class GetReport_adminResult
	{
		
		private System.Nullable<int> _RYEAR;
		
		private string _RMONTH;
		
		private System.Nullable<int> _RMONTH1;
		
		private System.Nullable<int> _Document_Uploaded;
		
		public GetReport_adminResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RYEAR", DbType="Int")]
		public System.Nullable<int> RYEAR
		{
			get
			{
				return this._RYEAR;
			}
			set
			{
				if ((this._RYEAR != value))
				{
					this._RYEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMONTH", DbType="NVarChar(30)")]
		public string RMONTH
		{
			get
			{
				return this._RMONTH;
			}
			set
			{
				if ((this._RMONTH != value))
				{
					this._RMONTH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMONTH1", DbType="Int")]
		public System.Nullable<int> RMONTH1
		{
			get
			{
				return this._RMONTH1;
			}
			set
			{
				if ((this._RMONTH1 != value))
				{
					this._RMONTH1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Document_Uploaded", DbType="Int")]
		public System.Nullable<int> Document_Uploaded
		{
			get
			{
				return this._Document_Uploaded;
			}
			set
			{
				if ((this._Document_Uploaded != value))
				{
					this._Document_Uploaded = value;
				}
			}
		}
	}
	
	public partial class GetAnalysisResult
	{
		
		private System.Nullable<int> _RES;
		
		public GetAnalysisResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES", DbType="Int")]
		public System.Nullable<int> RES
		{
			get
			{
				return this._RES;
			}
			set
			{
				if ((this._RES != value))
				{
					this._RES = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
