-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.2.8-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for dms
CREATE DATABASE IF NOT EXISTS `dms` /*!40100 DEFAULT CHARACTER SET cp1256 */;
USE `dms`;

-- Dumping structure for table dms.bookmark
CREATE TABLE IF NOT EXISTS `bookmark` (
  `BOOKMARK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) NOT NULL,
  `DOCUMENT_ID` int(11) NOT NULL,
  `OWNER_ID` int(11) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` date NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`BOOKMARK_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.bookmark: 0 rows
DELETE FROM `bookmark`;
/*!40000 ALTER TABLE `bookmark` DISABLE KEYS */;
/*!40000 ALTER TABLE `bookmark` ENABLE KEYS */;

-- Dumping structure for table dms.briefcase
CREATE TABLE IF NOT EXISTS `briefcase` (
  `BRIEFCASE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(250) NOT NULL,
  `OWNER_ID` int(11) NOT NULL,
  `IS_PUBLIC_Y_N` varchar(1) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  `CLIENT_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` date NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`BRIEFCASE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.briefcase: 0 rows
DELETE FROM `briefcase`;
/*!40000 ALTER TABLE `briefcase` DISABLE KEYS */;
/*!40000 ALTER TABLE `briefcase` ENABLE KEYS */;

-- Dumping structure for table dms.briefcase_document
CREATE TABLE IF NOT EXISTS `briefcase_document` (
  `BRIEFCASE_DOCUMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BRIEFCASE_ID` int(11) NOT NULL,
  `DOCUMENT_ID` int(1) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`BRIEFCASE_DOCUMENT_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.briefcase_document: 0 rows
DELETE FROM `briefcase_document`;
/*!40000 ALTER TABLE `briefcase_document` DISABLE KEYS */;
/*!40000 ALTER TABLE `briefcase_document` ENABLE KEYS */;

-- Dumping structure for table dms.d000020
CREATE TABLE IF NOT EXISTS `d000020` (
  `TABLE_NAME` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`TABLE_NAME`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000020: 0 rows
DELETE FROM `d000020`;
/*!40000 ALTER TABLE `d000020` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000020` ENABLE KEYS */;

-- Dumping structure for table dms.d000021
CREATE TABLE IF NOT EXISTS `d000021` (
  `D000021` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`D000021`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000021: 0 rows
DELETE FROM `d000021`;
/*!40000 ALTER TABLE `d000021` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000021` ENABLE KEYS */;

-- Dumping structure for table dms.d000022
CREATE TABLE IF NOT EXISTS `d000022` (
  `D000022` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`D000022`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000022: 0 rows
DELETE FROM `d000022`;
/*!40000 ALTER TABLE `d000022` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000022` ENABLE KEYS */;

-- Dumping structure for table dms.d000023
CREATE TABLE IF NOT EXISTS `d000023` (
  `D000023` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`D000023`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000023: 0 rows
DELETE FROM `d000023`;
/*!40000 ALTER TABLE `d000023` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000023` ENABLE KEYS */;

-- Dumping structure for table dms.d000025
CREATE TABLE IF NOT EXISTS `d000025` (
  `D000025_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`D000025_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000025: 0 rows
DELETE FROM `d000025`;
/*!40000 ALTER TABLE `d000025` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000025` ENABLE KEYS */;

-- Dumping structure for table dms.d000026
CREATE TABLE IF NOT EXISTS `d000026` (
  `D000026_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`D000026_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000026: 0 rows
DELETE FROM `d000026`;
/*!40000 ALTER TABLE `d000026` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000026` ENABLE KEYS */;

-- Dumping structure for table dms.d000027
CREATE TABLE IF NOT EXISTS `d000027` (
  `D000027_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000027_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000027: 0 rows
DELETE FROM `d000027`;
/*!40000 ALTER TABLE `d000027` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000027` ENABLE KEYS */;

-- Dumping structure for table dms.d000028
CREATE TABLE IF NOT EXISTS `d000028` (
  `D000028_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000028_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000028: 0 rows
DELETE FROM `d000028`;
/*!40000 ALTER TABLE `d000028` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000028` ENABLE KEYS */;

-- Dumping structure for table dms.d000029
CREATE TABLE IF NOT EXISTS `d000029` (
  `D000029_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000029_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000029: 0 rows
DELETE FROM `d000029`;
/*!40000 ALTER TABLE `d000029` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000029` ENABLE KEYS */;

-- Dumping structure for table dms.d000030
CREATE TABLE IF NOT EXISTS `d000030` (
  `D000030_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000030_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000030: 0 rows
DELETE FROM `d000030`;
/*!40000 ALTER TABLE `d000030` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000030` ENABLE KEYS */;

-- Dumping structure for table dms.d000031
CREATE TABLE IF NOT EXISTS `d000031` (
  `D000031_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000031_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000031: 0 rows
DELETE FROM `d000031`;
/*!40000 ALTER TABLE `d000031` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000031` ENABLE KEYS */;

-- Dumping structure for table dms.d000032
CREATE TABLE IF NOT EXISTS `d000032` (
  `D000032_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000032_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000032: 0 rows
DELETE FROM `d000032`;
/*!40000 ALTER TABLE `d000032` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000032` ENABLE KEYS */;

-- Dumping structure for table dms.d000033
CREATE TABLE IF NOT EXISTS `d000033` (
  `D000033_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000033_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000033: 0 rows
DELETE FROM `d000033`;
/*!40000 ALTER TABLE `d000033` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000033` ENABLE KEYS */;

-- Dumping structure for table dms.d000034
CREATE TABLE IF NOT EXISTS `d000034` (
  `D000034_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000034_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000034: 0 rows
DELETE FROM `d000034`;
/*!40000 ALTER TABLE `d000034` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000034` ENABLE KEYS */;

-- Dumping structure for table dms.d000035
CREATE TABLE IF NOT EXISTS `d000035` (
  `D000035_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000035_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000035: 0 rows
DELETE FROM `d000035`;
/*!40000 ALTER TABLE `d000035` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000035` ENABLE KEYS */;

-- Dumping structure for table dms.d000036
CREATE TABLE IF NOT EXISTS `d000036` (
  `D000036_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000036_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000036: 0 rows
DELETE FROM `d000036`;
/*!40000 ALTER TABLE `d000036` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000036` ENABLE KEYS */;

-- Dumping structure for table dms.d000037
CREATE TABLE IF NOT EXISTS `d000037` (
  `D000037_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000037_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000037: 0 rows
DELETE FROM `d000037`;
/*!40000 ALTER TABLE `d000037` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000037` ENABLE KEYS */;

-- Dumping structure for table dms.d000038
CREATE TABLE IF NOT EXISTS `d000038` (
  `D000038_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000038_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000038: 0 rows
DELETE FROM `d000038`;
/*!40000 ALTER TABLE `d000038` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000038` ENABLE KEYS */;

-- Dumping structure for table dms.d000039
CREATE TABLE IF NOT EXISTS `d000039` (
  `D000039_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000039_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000039: 0 rows
DELETE FROM `d000039`;
/*!40000 ALTER TABLE `d000039` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000039` ENABLE KEYS */;

-- Dumping structure for table dms.d000040
CREATE TABLE IF NOT EXISTS `d000040` (
  `D000040_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000040_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000040: 0 rows
DELETE FROM `d000040`;
/*!40000 ALTER TABLE `d000040` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000040` ENABLE KEYS */;

-- Dumping structure for table dms.d000041
CREATE TABLE IF NOT EXISTS `d000041` (
  `D000041_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000041_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000041: 0 rows
DELETE FROM `d000041`;
/*!40000 ALTER TABLE `d000041` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000041` ENABLE KEYS */;

-- Dumping structure for table dms.d000042
CREATE TABLE IF NOT EXISTS `d000042` (
  `D000042_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000042_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000042: 0 rows
DELETE FROM `d000042`;
/*!40000 ALTER TABLE `d000042` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000042` ENABLE KEYS */;

-- Dumping structure for table dms.d000043
CREATE TABLE IF NOT EXISTS `d000043` (
  `D000043_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000043_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000043: 0 rows
DELETE FROM `d000043`;
/*!40000 ALTER TABLE `d000043` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000043` ENABLE KEYS */;

-- Dumping structure for table dms.d000044
CREATE TABLE IF NOT EXISTS `d000044` (
  `D000044_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000044_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000044: 0 rows
DELETE FROM `d000044`;
/*!40000 ALTER TABLE `d000044` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000044` ENABLE KEYS */;

-- Dumping structure for table dms.d000045
CREATE TABLE IF NOT EXISTS `d000045` (
  `D000045_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000045_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000045: 0 rows
DELETE FROM `d000045`;
/*!40000 ALTER TABLE `d000045` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000045` ENABLE KEYS */;

-- Dumping structure for table dms.d000046
CREATE TABLE IF NOT EXISTS `d000046` (
  `D000046_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000046_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000046: 0 rows
DELETE FROM `d000046`;
/*!40000 ALTER TABLE `d000046` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000046` ENABLE KEYS */;

-- Dumping structure for table dms.d000047
CREATE TABLE IF NOT EXISTS `d000047` (
  `D000047_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000047_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000047: 0 rows
DELETE FROM `d000047`;
/*!40000 ALTER TABLE `d000047` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000047` ENABLE KEYS */;

-- Dumping structure for table dms.d000048
CREATE TABLE IF NOT EXISTS `d000048` (
  `D000048_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`D000048_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.d000048: 0 rows
DELETE FROM `d000048`;
/*!40000 ALTER TABLE `d000048` DISABLE KEYS */;
/*!40000 ALTER TABLE `d000048` ENABLE KEYS */;

-- Dumping structure for table dms.document
CREATE TABLE IF NOT EXISTS `document` (
  `DOCUMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FILE_NAME` varchar(250) NOT NULL,
  `DESC_AR` varchar(250) DEFAULT NULL,
  `DESC_EN` varchar(250) DEFAULT NULL,
  `FILE_SIZE` int(11) NOT NULL,
  `EXTENSION_ID` int(11) NOT NULL,
  `TEMPLATE_ID` int(11) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  `IS_LOCKED_Y_N` varchar(1) NOT NULL,
  `VERSION` varchar(10) NOT NULL,
  `ACCESS_COUNT` int(11) NOT NULL,
  `EXPIRED_DATE_G` date DEFAULT NULL,
  `EXPIRED_DATE_H` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`DOCUMENT_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.document: 0 rows
DELETE FROM `document`;
/*!40000 ALTER TABLE `document` DISABLE KEYS */;
/*!40000 ALTER TABLE `document` ENABLE KEYS */;

-- Dumping structure for table dms.document_access
CREATE TABLE IF NOT EXISTS `document_access` (
  `DOCUMENT_ACCESS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `ACCESS_DATE_G` date NOT NULL,
  `ACCESS_DATE_H` varchar(10) NOT NULL,
  `IP` varchar(50) NOT NULL,
  `DOCUMENT_ID` int(11) NOT NULL,
  PRIMARY KEY (`DOCUMENT_ACCESS_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.document_access: 0 rows
DELETE FROM `document_access`;
/*!40000 ALTER TABLE `document_access` DISABLE KEYS */;
/*!40000 ALTER TABLE `document_access` ENABLE KEYS */;

-- Dumping structure for table dms.document_tag
CREATE TABLE IF NOT EXISTS `document_tag` (
  `DOCUMENT_TAG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOCUMENT_ID` int(11) NOT NULL,
  `TAG_ID` int(11) DEFAULT NULL,
  `IS_ACTIVE_Y_N` varchar(1) DEFAULT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`DOCUMENT_TAG_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.document_tag: 0 rows
DELETE FROM `document_tag`;
/*!40000 ALTER TABLE `document_tag` DISABLE KEYS */;
/*!40000 ALTER TABLE `document_tag` ENABLE KEYS */;

-- Dumping structure for table dms.extension
CREATE TABLE IF NOT EXISTS `extension` (
  `EXTENSION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(50) NOT NULL,
  `EXT` varchar(7) NOT NULL,
  `FILE_TYPE_ID` int(11) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  PRIMARY KEY (`EXTENSION_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=53 DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.extension: 2 rows
DELETE FROM `extension`;
/*!40000 ALTER TABLE `extension` DISABLE KEYS */;
INSERT INTO `extension` (`EXTENSION_ID`, `NAME_AR`, `NAME_EN`, `EXT`, `FILE_TYPE_ID`, `IS_ACTIVE_Y_N`) VALUES
	(49, 'Extn 1', 'Extn 1', '.Png', 5, 'Y'),
	(50, 'Extn 2', 'Extn 2', '.pdf', 5, 'Y');
/*!40000 ALTER TABLE `extension` ENABLE KEYS */;

-- Dumping structure for table dms.f000020
CREATE TABLE IF NOT EXISTS `f000020` (
  `TABLE_NAME` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`TABLE_NAME`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000020: 0 rows
DELETE FROM `f000020`;
/*!40000 ALTER TABLE `f000020` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000020` ENABLE KEYS */;

-- Dumping structure for table dms.f000021
CREATE TABLE IF NOT EXISTS `f000021` (
  `F000021` int(11) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`F000021`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000021: 0 rows
DELETE FROM `f000021`;
/*!40000 ALTER TABLE `f000021` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000021` ENABLE KEYS */;

-- Dumping structure for table dms.f000022
CREATE TABLE IF NOT EXISTS `f000022` (
  `F000022` int(11) NOT NULL AUTO_INCREMENT,
  `D000022` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`F000022`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000022: 0 rows
DELETE FROM `f000022`;
/*!40000 ALTER TABLE `f000022` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000022` ENABLE KEYS */;

-- Dumping structure for table dms.f000023
CREATE TABLE IF NOT EXISTS `f000023` (
  `F000023` int(11) NOT NULL AUTO_INCREMENT,
  `D000023` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`F000023`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000023: 0 rows
DELETE FROM `f000023`;
/*!40000 ALTER TABLE `f000023` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000023` ENABLE KEYS */;

-- Dumping structure for table dms.f000025
CREATE TABLE IF NOT EXISTS `f000025` (
  `F000025_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000025` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`F000025_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000025: 0 rows
DELETE FROM `f000025`;
/*!40000 ALTER TABLE `f000025` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000025` ENABLE KEYS */;

-- Dumping structure for table dms.f000026
CREATE TABLE IF NOT EXISTS `f000026` (
  `F000026_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000026_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(250) NOT NULL,
  `UPDATED_IN` datetime NOT NULL,
  PRIMARY KEY (`F000026_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000026: 0 rows
DELETE FROM `f000026`;
/*!40000 ALTER TABLE `f000026` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000026` ENABLE KEYS */;

-- Dumping structure for table dms.f000027
CREATE TABLE IF NOT EXISTS `f000027` (
  `F000027_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000027_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000027_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000027: 0 rows
DELETE FROM `f000027`;
/*!40000 ALTER TABLE `f000027` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000027` ENABLE KEYS */;

-- Dumping structure for table dms.f000028
CREATE TABLE IF NOT EXISTS `f000028` (
  `F000028_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000028_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000028_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000028: 0 rows
DELETE FROM `f000028`;
/*!40000 ALTER TABLE `f000028` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000028` ENABLE KEYS */;

-- Dumping structure for table dms.f000029
CREATE TABLE IF NOT EXISTS `f000029` (
  `F000029_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000029_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000029_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000029: 0 rows
DELETE FROM `f000029`;
/*!40000 ALTER TABLE `f000029` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000029` ENABLE KEYS */;

-- Dumping structure for table dms.f000030
CREATE TABLE IF NOT EXISTS `f000030` (
  `F000030_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000030_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000030_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000030: 0 rows
DELETE FROM `f000030`;
/*!40000 ALTER TABLE `f000030` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000030` ENABLE KEYS */;

-- Dumping structure for table dms.f000031
CREATE TABLE IF NOT EXISTS `f000031` (
  `F000031_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000031_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000031_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000031: 0 rows
DELETE FROM `f000031`;
/*!40000 ALTER TABLE `f000031` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000031` ENABLE KEYS */;

-- Dumping structure for table dms.f000032
CREATE TABLE IF NOT EXISTS `f000032` (
  `F000032_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000032_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000032_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000032: 0 rows
DELETE FROM `f000032`;
/*!40000 ALTER TABLE `f000032` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000032` ENABLE KEYS */;

-- Dumping structure for table dms.f000033
CREATE TABLE IF NOT EXISTS `f000033` (
  `F000033_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000033_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000033_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000033: 0 rows
DELETE FROM `f000033`;
/*!40000 ALTER TABLE `f000033` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000033` ENABLE KEYS */;

-- Dumping structure for table dms.f000034
CREATE TABLE IF NOT EXISTS `f000034` (
  `F000034_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000034_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000034_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000034: 0 rows
DELETE FROM `f000034`;
/*!40000 ALTER TABLE `f000034` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000034` ENABLE KEYS */;

-- Dumping structure for table dms.f000035
CREATE TABLE IF NOT EXISTS `f000035` (
  `F000035_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000035_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000035_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000035: 0 rows
DELETE FROM `f000035`;
/*!40000 ALTER TABLE `f000035` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000035` ENABLE KEYS */;

-- Dumping structure for table dms.f000036
CREATE TABLE IF NOT EXISTS `f000036` (
  `F000036_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000036_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000036_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000036: 0 rows
DELETE FROM `f000036`;
/*!40000 ALTER TABLE `f000036` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000036` ENABLE KEYS */;

-- Dumping structure for table dms.f000037
CREATE TABLE IF NOT EXISTS `f000037` (
  `F000037_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000037_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000037_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000037: 0 rows
DELETE FROM `f000037`;
/*!40000 ALTER TABLE `f000037` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000037` ENABLE KEYS */;

-- Dumping structure for table dms.f000038
CREATE TABLE IF NOT EXISTS `f000038` (
  `F000038_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000038_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000038_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000038: 0 rows
DELETE FROM `f000038`;
/*!40000 ALTER TABLE `f000038` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000038` ENABLE KEYS */;

-- Dumping structure for table dms.f000039
CREATE TABLE IF NOT EXISTS `f000039` (
  `F000039_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000039_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000039_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000039: 0 rows
DELETE FROM `f000039`;
/*!40000 ALTER TABLE `f000039` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000039` ENABLE KEYS */;

-- Dumping structure for table dms.f000040
CREATE TABLE IF NOT EXISTS `f000040` (
  `F000040_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000040_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000040_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000040: 0 rows
DELETE FROM `f000040`;
/*!40000 ALTER TABLE `f000040` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000040` ENABLE KEYS */;

-- Dumping structure for table dms.f000041
CREATE TABLE IF NOT EXISTS `f000041` (
  `F000041_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000041_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000041_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000041: 0 rows
DELETE FROM `f000041`;
/*!40000 ALTER TABLE `f000041` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000041` ENABLE KEYS */;

-- Dumping structure for table dms.f000042
CREATE TABLE IF NOT EXISTS `f000042` (
  `F000042_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000042_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000042_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000042: 0 rows
DELETE FROM `f000042`;
/*!40000 ALTER TABLE `f000042` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000042` ENABLE KEYS */;

-- Dumping structure for table dms.f000043
CREATE TABLE IF NOT EXISTS `f000043` (
  `F000043_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000043_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000043_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000043: 0 rows
DELETE FROM `f000043`;
/*!40000 ALTER TABLE `f000043` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000043` ENABLE KEYS */;

-- Dumping structure for table dms.f000044
CREATE TABLE IF NOT EXISTS `f000044` (
  `F000044_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000044_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000044_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000044: 0 rows
DELETE FROM `f000044`;
/*!40000 ALTER TABLE `f000044` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000044` ENABLE KEYS */;

-- Dumping structure for table dms.f000045
CREATE TABLE IF NOT EXISTS `f000045` (
  `F000045_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000045_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000045_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000045: 0 rows
DELETE FROM `f000045`;
/*!40000 ALTER TABLE `f000045` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000045` ENABLE KEYS */;

-- Dumping structure for table dms.f000046
CREATE TABLE IF NOT EXISTS `f000046` (
  `F000046_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000046_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000046_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000046: 0 rows
DELETE FROM `f000046`;
/*!40000 ALTER TABLE `f000046` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000046` ENABLE KEYS */;

-- Dumping structure for table dms.f000047
CREATE TABLE IF NOT EXISTS `f000047` (
  `F000047_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000047_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000047_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000047: 0 rows
DELETE FROM `f000047`;
/*!40000 ALTER TABLE `f000047` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000047` ENABLE KEYS */;

-- Dumping structure for table dms.f000048
CREATE TABLE IF NOT EXISTS `f000048` (
  `F000048_ID` int(11) NOT NULL AUTO_INCREMENT,
  `D000048_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`F000048_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.f000048: 0 rows
DELETE FROM `f000048`;
/*!40000 ALTER TABLE `f000048` DISABLE KEYS */;
/*!40000 ALTER TABLE `f000048` ENABLE KEYS */;

-- Dumping structure for table dms.field
CREATE TABLE IF NOT EXISTS `field` (
  `FIELD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(250) NOT NULL,
  `SQL_CODE` varchar(150) NOT NULL,
  `MAX_LENGHT` int(11) NOT NULL,
  `FIELD_TYPE_ID` int(11) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  `CLIENT_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` datetime DEFAULT NULL,
  PRIMARY KEY (`FIELD_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.field: 6 rows
DELETE FROM `field`;
/*!40000 ALTER TABLE `field` DISABLE KEYS */;
INSERT INTO `field` (`FIELD_ID`, `NAME_AR`, `NAME_EN`, `SQL_CODE`, `MAX_LENGHT`, `FIELD_TYPE_ID`, `IS_ACTIVE_Y_N`, `CLIENT_ID`, `CREATED_BY`, `CREATED_IN`, `UPDATED_BY`, `UPDATED_IN`) VALUES
	(4, 'Country', 'Country', 'COUNTRY', 25, 1, 'Y', 4, 1, '2017-08-22 17:30:45', 1, '2017-08-26 11:28:52'),
	(3, 'Test', 'Test', 'Test', 25, 7, 'Y', 4, 1, '2017-08-22 17:04:00', NULL, NULL),
	(9, 'Employee Number', 'Employee Number', 'EMP_NO', 20, 12, 'Y', 4, 1, '2017-08-26 14:59:58', NULL, NULL),
	(7, 'TEST1', 'TEST1', 'TEST1', 5200, 8, 'Y', 44, 1, '2017-08-26 10:17:43', 1, '2017-08-26 11:29:01'),
	(8, 'Dean1', 'Dean2', 'Dean3', 52369, 8, 'Y', 1, 1, '2017-08-26 11:19:14', 1, '2017-08-26 11:29:12'),
	(10, 'Employee Name', 'Employee Name', 'EMP_NAME', 250, 13, 'Y', 4, 1, '2017-08-26 15:00:27', NULL, NULL);
/*!40000 ALTER TABLE `field` ENABLE KEYS */;

-- Dumping structure for table dms.field_type
CREATE TABLE IF NOT EXISTS `field_type` (
  `FIELD_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(250) NOT NULL,
  `SQL_TYPE` varchar(50) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`FIELD_TYPE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.field_type: 4 rows
DELETE FROM `field_type`;
/*!40000 ALTER TABLE `field_type` DISABLE KEYS */;
INSERT INTO `field_type` (`FIELD_TYPE_ID`, `NAME_AR`, `NAME_EN`, `SQL_TYPE`, `IS_ACTIVE_Y_N`) VALUES
	(14, 'Georgian Date', 'Georgian Date', 'Date', 'Y'),
	(13, 'Text', 'Text', 'String', 'Y'),
	(1, 'List', 'List', 'List', 'Y'),
	(12, 'Number', 'Number', 'Number', 'Y');
/*!40000 ALTER TABLE `field_type` ENABLE KEYS */;

-- Dumping structure for table dms.file_type
CREATE TABLE IF NOT EXISTS `file_type` (
  `FILE_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(250) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  PRIMARY KEY (`FILE_TYPE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.file_type: 2 rows
DELETE FROM `file_type`;
/*!40000 ALTER TABLE `file_type` DISABLE KEYS */;
INSERT INTO `file_type` (`FILE_TYPE_ID`, `NAME_AR`, `NAME_EN`, `IS_ACTIVE_Y_N`) VALUES
	(4, 'Type 1', 'Type 1', 'Y'),
	(5, 'Type 2', 'Type 2', 'Y');
/*!40000 ALTER TABLE `file_type` ENABLE KEYS */;

-- Dumping structure for table dms.hotlink
CREATE TABLE IF NOT EXISTS `hotlink` (
  `HOTLINK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(250) NOT NULL,
  `DESC_AR` varchar(500) DEFAULT NULL,
  `DESC_EN` varchar(500) DEFAULT NULL,
  `MASTER_TEMPLATE` int(11) NOT NULL,
  `DETAIL_TEMPLATE` int(11) NOT NULL,
  `FIELD_ID` int(11) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`HOTLINK_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.hotlink: 0 rows
DELETE FROM `hotlink`;
/*!40000 ALTER TABLE `hotlink` DISABLE KEYS */;
/*!40000 ALTER TABLE `hotlink` ENABLE KEYS */;

-- Dumping structure for table dms.list_item
CREATE TABLE IF NOT EXISTS `list_item` (
  `LIST_ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIELD_ID` int(11) NOT NULL,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(250) NOT NULL,
  `ORDINAL` int(11) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`LIST_ITEM_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.list_item: 3 rows
DELETE FROM `list_item`;
/*!40000 ALTER TABLE `list_item` DISABLE KEYS */;
INSERT INTO `list_item` (`LIST_ITEM_ID`, `FIELD_ID`, `NAME_AR`, `NAME_EN`, `ORDINAL`, `IS_ACTIVE_Y_N`) VALUES
	(3, 4, 'Test', 'test', 1, 'Y'),
	(5, 7, 'TEST', 'TEST', 1, 'Y'),
	(9, 4, 'test2', 'test2', 5, 'Y');
/*!40000 ALTER TABLE `list_item` ENABLE KEYS */;

-- Dumping structure for table dms.permission
CREATE TABLE IF NOT EXISTS `permission` (
  `PERMISSION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(250) NOT NULL,
  `CODE` varchar(10) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  PRIMARY KEY (`PERMISSION_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.permission: 0 rows
DELETE FROM `permission`;
/*!40000 ALTER TABLE `permission` DISABLE KEYS */;
/*!40000 ALTER TABLE `permission` ENABLE KEYS */;

-- Dumping structure for procedure dms.PRC_EXTENSION_DEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_EXTENSION_DEL`(

	IN `PEXTENSION_ID` INT(11),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   DELETE FROM EXTENSION 

   WHERE EXTENSION_ID = PEXTENSION_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_EXTENSION_INS
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_EXTENSION_INS`(

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PEXT` VARCHAR(7),

	IN `PFILE_TYPE_ID` INT(11),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   INSERT INTO EXTENSION(NAME_AR,NAME_EN,EXT,FILE_TYPE_ID,IS_ACTIVE_Y_N)

	VALUES(PNAME_AR,PNAME_EN,PEXT,PFILE_TYPE_ID,PIS_ACTIVE_Y_N);

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_EXTENSION_SEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_EXTENSION_SEL`(

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	









)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   SELECT ext.*, fle_type.NAME_EN as FILE_TYPE_NAME FROM EXTENSION ext JOIN FILE_TYPE fle_type on ext.FILE_TYPE_ID = fle_type.FILE_TYPE_ID;

  

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_EXTENSION_UPD
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_EXTENSION_UPD`(

	IN `PEXTENSION_ID` INT(11),

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PEXT` VARCHAR(7),

	IN `PFILE_TYPE_ID` INT(11),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   UPDATE EXTENSION SET 

   NAME_AR = PNAME_AR,

   NAME_EN = PNAME_EN,

   EXT = PEXT,

   FILE_TYPE_ID = PFILE_TYPE_ID,

   IS_ACTIVE_Y_N = PIS_ACTIVE_Y_N

   WHERE EXTENSION_ID = PEXTENSION_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FIELD_DEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FIELD_DEL`(

	IN `PFIELD_ID` INT(11),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	

)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   DELETE FROM FIELD 

   WHERE FIELD_ID = PFIELD_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FIELD_INS
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FIELD_INS`(

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PSQL_CODE` VARCHAR(150),

	IN `PMAX_LENGHT` INT(11),

	IN `PFIELD_TYPE_ID` INT(11),

	IN `PCLIENT_ID` INT(11),

	IN `PUSER_ID` INT(11),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	





)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   INSERT INTO FIELD(NAME_AR,NAME_EN,SQL_CODE,MAX_LENGHT,FIELD_TYPE_ID,IS_ACTIVE_Y_N,CLIENT_ID,CREATED_BY,CREATED_IN)

	VALUES(PNAME_AR,PNAME_EN,PSQL_CODE,PMAX_LENGHT,PFIELD_TYPE_ID,PIS_ACTIVE_Y_N,PCLIENT_ID,PUSER_ID,CURRENT_TIMESTAMP);

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FIELD_SEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FIELD_SEL`(

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	











)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   SELECT Fld.*, fle_type.NAME_EN as FIELD_TYPE_NAME

	  FROM FIELD Fld JOIN FIELD_TYPE fle_type on Fld.FIELD_TYPE_ID = fle_type.FIELD_TYPE_ID;

  

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FIELD_SEL_TYPELIST
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FIELD_SEL_TYPELIST`(

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   SELECT Fld.*, fle_type.NAME_EN as FIELD_TYPE_NAME

	  FROM FIELD Fld JOIN FIELD_TYPE fle_type on Fld.FIELD_TYPE_ID = fle_type.FIELD_TYPE_ID

	  where fle_type.FIELD_TYPE_ID = 1;

  

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FIELD_TYPE_DEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FIELD_TYPE_DEL`(

	IN `PFIELD_TYPE_ID` INT(11),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   DELETE FROM FIELD_TYPE 

   WHERE FIELD_TYPE_ID = PFIELD_TYPE_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FIELD_TYPE_INS
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FIELD_TYPE_INS`(

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PSQL_TYPE` VARCHAR(50),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   INSERT INTO FIELD_TYPE(NAME_AR,NAME_EN,SQL_TYPE,IS_ACTIVE_Y_N)

	VALUES(PNAME_AR,PNAME_EN,PSQL_TYPE,PIS_ACTIVE_Y_N);

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FIELD_TYPE_SEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FIELD_TYPE_SEL`(

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   SELECT * FROM FIELD_TYPE ;

  

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FIELD_TYPE_UPD
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FIELD_TYPE_UPD`(

	IN `PFIELD_TYPE_ID` INT(11),

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PSQL_TYPE` VARCHAR(50),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	





)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   UPDATE FIELD_TYPE SET 

   NAME_AR = PNAME_AR,

   NAME_EN = PNAME_EN,

   SQL_TYPE = PSQL_TYPE,

   IS_ACTIVE_Y_N = PIS_ACTIVE_Y_N

   WHERE FIELD_TYPE_ID = PFIELD_TYPE_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FIELD_UPD
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FIELD_UPD`(

	IN `PFIELD_ID` INT(11),

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PSQL_CODE` VARCHAR(150),

	IN `PMAX_LENGHT` INT(11),

	IN `PFIELD_TYPE_ID` INT(11),

	IN `PCLIENT_ID` INT(11),

	IN `PUSER_ID` INT(11),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   UPDATE FIELD SET 

   NAME_AR = PNAME_AR,

   NAME_EN = PNAME_EN,

   SQL_CODE = PSQL_CODE,

   MAX_LENGHT = PMAX_LENGHT,

   FIELD_TYPE_ID = PFIELD_TYPE_ID,

   IS_ACTIVE_Y_N = PIS_ACTIVE_Y_N,

   CLIENT_ID = PCLIENT_ID,

   UPDATED_BY = PUSER_ID,

   UPDATED_IN = CURRENT_TIMESTAMP

   WHERE FIELD_ID = PFIELD_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FILE_TYPE_DEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FILE_TYPE_DEL`(

	IN `PFILE_TYPE_ID` INT(11),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   DELETE FROM FILE_TYPE 

   WHERE FILE_TYPE_ID = PFILE_TYPE_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FILE_TYPE_INS
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FILE_TYPE_INS`(

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   INSERT INTO FILE_TYPE(NAME_AR,NAME_EN,IS_ACTIVE_Y_N)

	VALUES(PNAME_AR,PNAME_EN,PIS_ACTIVE_Y_N);

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FILE_TYPE_SEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FILE_TYPE_SEL`(

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   SELECT * FROM FILE_TYPE ;

  

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_FILE_TYPE_UPD
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_FILE_TYPE_UPD`(

	IN `PFILE_TYPE_ID` INT(11),

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   UPDATE FILE_TYPE SET 

   NAME_AR = PNAME_AR,

   NAME_EN = PNAME_EN,

   IS_ACTIVE_Y_N = PIS_ACTIVE_Y_N

   WHERE FILE_TYPE_ID = PFILE_TYPE_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_LIST_ITEM_DEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_LIST_ITEM_DEL`(

	IN `PLIST_ITEM_ID` INT(11),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	

)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   DELETE FROM LIST_ITEM 

   WHERE LIST_ITEM_ID = PLIST_ITEM_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_LIST_ITEM_INS
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_LIST_ITEM_INS`(

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PORDINAL` INT(11),

	IN `PFIELD_ID` INT(11),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	





)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   INSERT INTO LIST_ITEM(FIELD_ID,NAME_AR,NAME_EN,ORDINAL,IS_ACTIVE_Y_N)

	VALUES(PFIELD_ID,PNAME_AR,PNAME_EN,PORDINAL,PIS_ACTIVE_Y_N);

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_LIST_ITEM_SEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_LIST_ITEM_SEL`(

	IN `PFIELD_ID` INT(11),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	







)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   SELECT li.*, f.NAME_EN as FIELD_NAME FROM LIST_ITEM li JOIN FIELD f on li.FIELD_ID = f.FIELD_ID where li.FIELD_ID = PFIELD_ID;

  

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_LIST_ITEM_UPD
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_LIST_ITEM_UPD`(

	IN `PLIST_ITEM_ID` INT(11),

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PFIELD_ID` INT(11),

	IN `PORDINAL` INT(11),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	





)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   UPDATE LIST_ITEM SET 

   FIELD_ID = PFIELD_ID,

   NAME_AR = PNAME_AR,

   NAME_EN = PNAME_EN,

   ORDINAL = PORDINAL,

   IS_ACTIVE_Y_N = PIS_ACTIVE_Y_N

   WHERE LIST_ITEM_ID = PLIST_ITEM_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_ROLE_DEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_ROLE_DEL`(

	IN `PROLE_ID` INT(11),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   DELETE FROM ROLE 

   WHERE ROLE_ID = PROLE_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_ROLE_INS
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_ROLE_INS`(

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PIS_READ_Y_N` VARCHAR(1),

	IN `PIS_ADD_Y_N` VARCHAR(1),

	IN `PIS_UPDATE_Y_N` VARCHAR(1),

	IN `PIS_DELETE_Y_N` VARCHAR(1),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   INSERT INTO ROLE(NAME_AR,NAME_EN,IS_READ_Y_N,IS_ADD_Y_N,IS_UPDATE_Y_N,IS_DELETE_Y_N,IS_ACTIVE_Y_N)

	VALUES(PNAME_AR,PNAME_EN,PIS_READ_Y_N,PIS_ADD_Y_N,PIS_UPDATE_Y_N,PIS_DELETE_Y_N,PIS_ACTIVE_Y_N);

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_ROLE_SEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_ROLE_SEL`(

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	

)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   SELECT * FROM ROLE ;

  

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_ROLE_UPD
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_ROLE_UPD`(

	IN `PROLE_ID` INT(11),

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PIS_READ_Y_N` VARCHAR(1),

	IN `PIS_ADD_Y_N` VARCHAR(1),

	IN `PIS_UPDATE_Y_N` VARCHAR(1),

	IN `PIS_DELETE_Y_N` VARCHAR(1),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   UPDATE ROLE SET 

   NAME_AR = PNAME_AR,

   NAME_EN = PNAME_EN,

   IS_READ_Y_N = PIS_READ_Y_N,

   IS_ADD_Y_N = PIS_ADD_Y_N,

   IS_UPDATE_Y_N = PIS_UPDATE_Y_N,

   IS_DELETE_Y_N = PIS_DELETE_Y_N,

   IS_ACTIVE_Y_N = PIS_ACTIVE_Y_N

   WHERE ROLE_ID = PROLE_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_TEMPLATE_COPY
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_TEMPLATE_COPY`(

	IN `PTEMPLATE_ID` VARCHAR(100),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)



)
BEGIN

	DECLARE LASTINSERTID INT;

	DECLARE DTABLE VARCHAR(7);

	DECLARE FTABLE VARCHAR(7);

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   

   INSERT INTO TEMPLATE(NAME_AR,NAME_EN,DESC_AR,DESC_EN,STORAGE_LOCATION,MAX_FILE_SIZE,MAX_FILE_COUNT,MAX_SIZE,IS_PUBLIC_Y_N,IS_ACTIVE_Y_N,CLIENT_ID,CREATED_BY, CREATED_IN)

	SELECT NAME_AR,NAME_EN,DESC_AR,DESC_EN,STORAGE_LOCATION,MAX_FILE_SIZE,MAX_FILE_COUNT,MAX_SIZE,IS_PUBLIC_Y_N,IS_ACTIVE_Y_N,CLIENT_ID,CREATED_BY, CURRENT_TIMESTAMP FROM TEMPLATE where TEMPLATE_ID = PTEMPLATE_ID;

	SET LASTINSERTID = LAST_INSERT_ID();

	SET DTABLE =CONCAT('D',CAST(LPAD(LASTINSERTID,6,'0') AS CHAR(6)));

	SET FTABLE =CONCAT('F',CAST(LPAD(LASTINSERTID,6,'0') AS CHAR(6)));

	begin

	

	UPDATE TEMPLATE SET DATE_TABLE = DTABLE, FILE_TABLE = FTABLE WHERE TEMPLATE_ID = LASTINSERTID;

	

	end;

	CALL DMS.PRC_TEMPLATE_DATATABLE_NEW(DTABLE,VERRORCODE,VERRORMSG);

	CALL DMS.PRC_TEMPLATE_FILETABLE_NEW(FTABLE,DTABLE,VERRORCODE,VERRORMSG);

	

	

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_TEMPLATE_DEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_TEMPLATE_DEL`(

	IN `PTEMPLATE_ID` INT(11),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	

)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   DELETE FROM TEMPLATE 

   WHERE TEMPLATE_ID = PTEMPLATE_ID;

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_TEMPLATE_FILETABLE_NEW
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_TEMPLATE_FILETABLE_NEW`(

	IN `TABLE_NAME` VARCHAR(100),

	IN `DATA_TABLE` VARCHAR(100),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)











)
BEGIN

	

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION



   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   BEGIN

   SET @SQL := CONCAT('CREATE TABLE IF NOT EXISTS `', UPPER(TABLE_NAME), '` (`',UPPER(TABLE_NAME),'_ID` INT(11) NOT NULL AUTO_INCREMENT, `',DATA_TABLE,'_ID` INT(11) NOT NULL, `CREATED_BY` INT(11) NOT NULL,  `CREATED_IN` DATETIME NOT NULL,  `UPDATED_BY` INT(11) DEFAULT NULL,  `UPDATED_IN` DATETIME DEFAULT NULL,  PRIMARY KEY (`',UPPER(TABLE_NAME),'_ID`)) ENGINE=MyISAM DEFAULT CHARSET=cp1256;');

        PREPARE stmt FROM @SQL;

    

  EXECUTE stmt;

   

	END;

  

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_TEMPLATE_INS
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_TEMPLATE_INS`(

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PDESC_AR` VARCHAR(500),

	IN `PDESC_EN` VARCHAR(500),

	IN `PSTORAGE_LOCATION` VARCHAR(500),

	IN `PMAX_FILE_SIZE` VARCHAR(11),

	IN `PMAX_FILE_COUNT` VARCHAR(11),

	IN `PMAX_SIZE` VARCHAR(11),

	IN `PIS_PUBLIC_Y_N` VARCHAR(1),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	IN `PCLIENT_ID` VARCHAR(11),

	IN `PUSER_ID` VARCHAR(11),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



















)
BEGIN

	DECLARE LASTINSERTID INT;

	DECLARE DTABLE VARCHAR(7);

	DECLARE FTABLE VARCHAR(7);

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   

   INSERT INTO TEMPLATE(NAME_AR,NAME_EN,DESC_AR,DESC_EN,STORAGE_LOCATION,MAX_FILE_SIZE,MAX_FILE_COUNT,MAX_SIZE,IS_PUBLIC_Y_N,IS_ACTIVE_Y_N,CLIENT_ID,CREATED_BY, CREATED_IN)

	VALUES(PNAME_AR,PNAME_EN,PDESC_AR,PDESC_EN,PSTORAGE_LOCATION,PMAX_FILE_SIZE,PMAX_FILE_COUNT,PMAX_SIZE,PIS_PUBLIC_Y_N,PIS_ACTIVE_Y_N,PCLIENT_ID,PUSER_ID, CURRENT_TIMESTAMP);

	SET LASTINSERTID = LAST_INSERT_ID();

	SET DTABLE =CONCAT('D',CAST(LPAD(LASTINSERTID,6,'0') AS CHAR(6)));

	SET FTABLE =CONCAT('F',CAST(LPAD(LASTINSERTID,6,'0') AS CHAR(6)));

	begin

	

	UPDATE TEMPLATE SET DATE_TABLE = DTABLE, FILE_TABLE = FTABLE WHERE TEMPLATE_ID = LASTINSERTID;

	

	end;

	CALL DMS.PRC_TEMPLATE_DATATABLE_NEW(DTABLE,VERRORCODE,VERRORMSG);

	CALL DMS.PRC_TEMPLATE_FILETABLE_NEW(FTABLE,DTABLE,VERRORCODE,VERRORMSG);

	

	

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_TEMPLATE_SEL
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_TEMPLATE_SEL`(

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	





)
BEGIN

	DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin

      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   SELECT Temp.*, clint.NAME_EN as CLIENT_NAME FROM TEMPLATE Temp JOIN SECURITY.`client` clint on Temp.CLIENT_ID = clint.CLIENT_ID ;

  

END//
DELIMITER ;

-- Dumping structure for procedure dms.PRC_TEMPLATE_UPD
DELIMITER //
CREATE DEFINER=`root`@`localhost` PROCEDURE `PRC_TEMPLATE_UPD`(

	IN `PTEMPLATE_ID` INT(11),

	IN `PNAME_AR` VARCHAR(250),

	IN `PNAME_EN` VARCHAR(250),

	IN `PDESC_AR` VARCHAR(500),

	IN `PDESC_EN` VARCHAR(500),

	IN `PSTORAGE_LOCATION` VARCHAR(500),

	IN `PMAX_FILE_SIZE` VARCHAR(11),

	IN `PMAX_FILE_COUNT` VARCHAR(11),

	IN `PMAX_SIZE` VARCHAR(11),

	IN `PIS_PUBLIC_Y_N` VARCHAR(1),

	IN `PIS_ACTIVE_Y_N` VARCHAR(1),

	IN `PCLIENT_ID` VARCHAR(11),

	IN `PUSER_ID` VARCHAR(11),

	OUT `VERRORCODE` VARCHAR(4000),

	OUT `VERRORMSG` VARCHAR(4000)

	



)
BEGIN

	

   DECLARE SWV_SQLCODE INT;

   DECLARE SWV_SQLERRM VARCHAR(4000);

   DECLARE EXIT HANDLER FOR NOT FOUND,SQLEXCEPTION

   begin



      GET DIAGNOSTICS CONDITION 1

      SWV_SQLCODE =  MYSQL_ERRNO,SWV_SQLERRM = MESSAGE_TEXT;

      SET VERRORCODE = SWV_SQLCODE;

      SET VERRORMSG = SWV_SQLERRM;

      CALL SECURITY.PRC_HANDLE_EXCEPTION(SUBSTRING_INDEX(USER(),'@',1),'DM_CDR',NULL,NULL,NULL,

      VERRORCODE,VERRORMSG);

   end;

   

   UPDATE TEMPLATE SET 

   NAME_AR = PNAME_AR,

   NAME_EN = PNAME_EN,

   DESC_AR = PDESC_AR,

   DESC_EN = PDESC_EN,

   STORAGE_LOCATION = PSTORAGE_LOCATION,

   MAX_FILE_SIZE = PMAX_FILE_SIZE,

   MAX_FILE_COUNT = PMAX_FILE_COUNT,

   MAX_SIZE = PMAX_SIZE,

   IS_PUBLIC_Y_N = PIS_PUBLIC_Y_N,

   IS_ACTIVE_Y_N = PIS_ACTIVE_Y_N,

   CLIENT_ID = PCLIENT_ID,

   UPDATED_BY = PUSER_ID,

   UPDATED_IN = CURRENT_TIMESTAMP

   

   WHERE TEMPLATE_ID = PTEMPLATE_ID;

END//
DELIMITER ;

-- Dumping structure for table dms.role
CREATE TABLE IF NOT EXISTS `role` (
  `ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(250) NOT NULL,
  `IS_READ_Y_N` varchar(1) NOT NULL,
  `IS_ADD_Y_N` varchar(1) NOT NULL,
  `IS_UPDATE_Y_N` varchar(1) NOT NULL,
  `IS_DELETE_Y_N` varchar(1) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.role: 1 rows
DELETE FROM `role`;
/*!40000 ALTER TABLE `role` DISABLE KEYS */;
INSERT INTO `role` (`ROLE_ID`, `NAME_AR`, `NAME_EN`, `IS_READ_Y_N`, `IS_ADD_Y_N`, `IS_UPDATE_Y_N`, `IS_DELETE_Y_N`, `IS_ACTIVE_Y_N`) VALUES
	(2, 'test', 'test', 'Y', 'Y', 'Y', 'Y', 'Y');
/*!40000 ALTER TABLE `role` ENABLE KEYS */;

-- Dumping structure for table dms.role_permission
CREATE TABLE IF NOT EXISTS `role_permission` (
  `ROLE_PERMISSION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_ID` int(11) NOT NULL,
  `PERMISSION_ID` int(11) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` date NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`ROLE_PERMISSION_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.role_permission: 0 rows
DELETE FROM `role_permission`;
/*!40000 ALTER TABLE `role_permission` DISABLE KEYS */;
/*!40000 ALTER TABLE `role_permission` ENABLE KEYS */;

-- Dumping structure for table dms.tag
CREATE TABLE IF NOT EXISTS `tag` (
  `TAG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) DEFAULT NULL,
  `CLIENT_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`TAG_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.tag: 0 rows
DELETE FROM `tag`;
/*!40000 ALTER TABLE `tag` DISABLE KEYS */;
/*!40000 ALTER TABLE `tag` ENABLE KEYS */;

-- Dumping structure for table dms.template
CREATE TABLE IF NOT EXISTS `template` (
  `TEMPLATE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(250) NOT NULL,
  `DESC_AR` varchar(500) NOT NULL,
  `DESC_EN` varchar(500) NOT NULL,
  `STORAGE_LOCATION` varchar(500) NOT NULL,
  `MAX_FILE_SIZE` int(11) DEFAULT NULL,
  `MAX_FILE_COUNT` int(11) NOT NULL,
  `MAX_SIZE` int(11) NOT NULL,
  `DATE_TABLE` varchar(7) DEFAULT NULL,
  `FILE_TABLE` varchar(7) DEFAULT NULL,
  `IS_PUBLIC_Y_N` varchar(1) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  `CLIENT_ID` int(11) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`TEMPLATE_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=49 DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.template: 4 rows
DELETE FROM `template`;
/*!40000 ALTER TABLE `template` DISABLE KEYS */;
INSERT INTO `template` (`TEMPLATE_ID`, `NAME_AR`, `NAME_EN`, `DESC_AR`, `DESC_EN`, `STORAGE_LOCATION`, `MAX_FILE_SIZE`, `MAX_FILE_COUNT`, `MAX_SIZE`, `DATE_TABLE`, `FILE_TABLE`, `IS_PUBLIC_Y_N`, `IS_ACTIVE_Y_N`, `CLIENT_ID`, `CREATED_BY`, `CREATED_IN`, `UPDATED_BY`, `UPDATED_IN`) VALUES
	(47, 'Test1', 'test1', 'test1', 'test1', 'test1', 1, 1, 1, 'D000047', 'F000047', 'Y', 'Y', 1, 1, '2017-08-28 14:46:03', NULL, NULL),
	(44, 'Test1', 'test1', 'test1', 'test1', 'test1', 1, 1, 1, 'D000044', 'F000044', 'Y', 'Y', 1, 1, '2017-08-28 14:42:59', NULL, NULL),
	(48, 'q', 'q', 'q', 'q', 'q', 1, 1, 1, 'D000048', 'F000048', 'Y', 'Y', 57, 1, '2017-08-28 15:24:35', NULL, NULL),
	(42, 'q', 'q', 'q', 'q', 'q', 1, 1, 1, 'D000042', 'F000042', 'Y', 'Y', 57, 1, '2017-08-28 14:23:10', NULL, NULL);
/*!40000 ALTER TABLE `template` ENABLE KEYS */;

-- Dumping structure for table dms.template_extension
CREATE TABLE IF NOT EXISTS `template_extension` (
  `TEMPLATE_EXTENSION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEMPLATE_ID` int(11) NOT NULL,
  `EXTENSION_ID` int(11) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` date NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`TEMPLATE_EXTENSION_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.template_extension: 0 rows
DELETE FROM `template_extension`;
/*!40000 ALTER TABLE `template_extension` DISABLE KEYS */;
/*!40000 ALTER TABLE `template_extension` ENABLE KEYS */;

-- Dumping structure for table dms.template_field
CREATE TABLE IF NOT EXISTS `template_field` (
  `TEMPLATE_FIELD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEMPLATE_ID` int(11) NOT NULL,
  `FIELD_ID` int(11) NOT NULL,
  `NAME_AR` varchar(250) NOT NULL,
  `NAME_EN` varchar(250) NOT NULL,
  `MAX_LENGHT` int(11) NOT NULL,
  `DEFAULT_VALUE` varchar(500) DEFAULT NULL,
  `ORDINAL` int(11) NOT NULL,
  `IS_REQUIRED_Y_N` varchar(1) NOT NULL,
  `IS_UNIQUE_Y_N` varchar(1) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`TEMPLATE_FIELD_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.template_field: 0 rows
DELETE FROM `template_field`;
/*!40000 ALTER TABLE `template_field` DISABLE KEYS */;
/*!40000 ALTER TABLE `template_field` ENABLE KEYS */;

-- Dumping structure for table dms.template_role
CREATE TABLE IF NOT EXISTS `template_role` (
  `TEMPLATE_ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEMPLATE_ID` int(11) NOT NULL,
  `ROLE_ID` int(11) NOT NULL,
  `CAN_CREATE_Y_N` varchar(1) DEFAULT NULL,
  `CAN_READ_Y_N` varchar(1) DEFAULT NULL,
  `CAN_WRITE_Y_N` varchar(1) DEFAULT NULL,
  `CAN_DELETE_Y_N` varchar(1) DEFAULT NULL,
  `CAN_PRINT_Y_N` varchar(1) DEFAULT NULL,
  `CAN_EMAIL_Y_N` varchar(1) DEFAULT NULL,
  `CAN_DOWNLOAD_Y_N` varchar(1) DEFAULT NULL,
  `CREATED_IN` int(11) NOT NULL,
  `CREATED_BY` date DEFAULT NULL,
  `UPDATED_IN` int(11) DEFAULT NULL,
  `UPDATED_BY` date DEFAULT NULL,
  PRIMARY KEY (`TEMPLATE_ROLE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.template_role: 0 rows
DELETE FROM `template_role`;
/*!40000 ALTER TABLE `template_role` DISABLE KEYS */;
/*!40000 ALTER TABLE `template_role` ENABLE KEYS */;

-- Dumping structure for table dms.user_role
CREATE TABLE IF NOT EXISTS `user_role` (
  `USER_ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `ROLE_ID` int(11) NOT NULL,
  `IS_ACTIVE_Y_N` varchar(1) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_IN` date NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_IN` date DEFAULT NULL,
  PRIMARY KEY (`USER_ROLE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1256;

-- Dumping data for table dms.user_role: 0 rows
DELETE FROM `user_role`;
/*!40000 ALTER TABLE `user_role` DISABLE KEYS */;
/*!40000 ALTER TABLE `user_role` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
